# Quantum Embedding

This tutorial shows several methods of embedding classical data into quantum states.

In [16]:
import pennylane as qml
from pennylane import numpy as np
from pennylane.templates.embeddings import AmplitudeEmbedding
from pennylane.templates.embeddings import AngleEmbedding
from pennylane.templates.embeddings import BasisEmbedding

1. Basis Embedding

In [29]:
x1 = np.array([0,1,0])
x2 = np.array([0,1,1])
dev = qml.device("default.qubit", wires = 3)

@qml.qnode(dev)
def Basis_Embedding():
    BasisEmbedding(x1, wires = [0,1,2])
    BasisEmbedding(x2, wires = [0,1,2])
    return qml.probs(wires = [0,1])

In [30]:
Basis_Embedding()

tensor([1., 0., 0., 0.], requires_grad=True)

2. Amplitude Embedding

In [31]:
x = [1, 2, 3, 4]

dev = qml.device("default.qubit", wires = 2)

@qml.qnode(dev)
def Amplitude_Embedding():
    AmplitudeEmbedding(x, wires = [0,1], normalize = True)
    return qml.probs(wires = [0, 1])

Amplitude_Embedding()
    

tensor([0.03333333, 0.13333333, 0.3       , 0.53333333], requires_grad=True)

3. AngleEmbedding

In [33]:
x = np.array([1,2,3,4]) / 10

dev = qml.device("default.qubit", wires = 4)

@qml.qnode(dev)
def Angle_Embedding():
    AngleEmbedding(x, wires = [0,1,2,3], rotation = 'X')
    return qml.probs(wires = [0,1])

In [34]:
Angle_Embedding()

tensor([9.87560268e-01, 9.94181506e-03, 2.47302134e-03, 2.48960206e-05], requires_grad=True)